coinType = "trx"
version = "v1"
port = ""
debug = true
walletType = "hot"
filePath = "./file"
isStartThread = true
mchId = "xtz"
orderId = "202102041847"
nodeUrl = ""


[auth]
encrypt = false
enable = false
user = ""
password = ""


[trx]
nodeUrl = ""
backUrls = [
""
]
user = ""
password = ""
